<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-CJGS9IU" failures="2" tests="2" name="Test(failed)" time="0.299" errors="0" timestamp="2023-07-10T16:13:30 IST">
  <testcase classname="RetryLogicDemo.TestCasesExample" name="TestCase01" time="0.069">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogicDemo.TestCasesExample.TestCase01(TestCasesExample.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TestCase01 -->
  <testcase classname="RetryLogicDemo.TestCasesExample" name="TestCase02" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogicDemo.TestCasesExample.TestCase02(TestCasesExample.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TestCase02 -->
  <testcase classname="RetryLogicDemo.TestCasesExample" name="TestCase03" time="0.0">
    <ignored/>
  </testcase> <!-- TestCase03 -->
</testsuite> <!-- Test(failed) -->
